require_relative 'board_spec'
# require_relative 'game_spec'
require_relative 'piece_spec'
require_relative 'pieces/bishop_spec'
require_relative 'pieces/king_spec'
require_relative 'pieces/knight_spec'
require_relative 'pieces/pawn_spec'
require_relative 'pieces/queen_spec'
require_relative 'pieces/rook_spec'
require_relative 'player_spec'
